/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ProveConfig {
  /** Target HTTPS server hostname (e.g. "api.example.com") */
  serverHost: string
  /** Target HTTPS server port (default 443) */
  serverPort?: number
  /** Notary/verifier TCP address (e.g. "127.0.0.1:7047") */
  notaryHost: string
  notaryPort?: number
  /** HTTP request to send */
  request: HttpRequest
  /** Maximum bytes to send (default 4096) */
  maxSentData?: number
  /** Maximum bytes to receive (default 16384) */
  maxRecvData?: number
  /**
   * Ranges of the response to reveal (byte offsets into recv transcript).
   * If omitted, the entire transcript is revealed.
   */
  revealRanges?: Array<RevealRange>
}
export interface HttpRequest {
  method: string
  path: string
  headers: Array<HttpHeader>
  body?: string
}
export interface HttpHeader {
  name: string
  value: string
}
export interface RevealRange {
  start: number
  end: number
}
export interface ProveResult {
  /** Serialized ProverOutput (commitments + secrets) as JSON */
  attestation: string
  /** SHA-256 of the attestation */
  attestationSha256: string
  /** Server hostname that was proven */
  serverName: string
  /** Sent transcript length in bytes */
  sentLen: number
  /** Received transcript length in bytes */
  recvLen: number
  backend: string
}
export interface VerifyConfig {
  /**
   * Serialized attestation data. Accepts:
   *   - JSON-serialized Presentation (full crypto verification)
   *   - Base64-encoded bincode Presentation (full crypto verification)
   *   - JSON-serialized ProverOutput (structural check only)
   */
  attestation: string
}
export interface VerifyResult {
  /** Whether the attestation is cryptographically valid */
  valid: boolean
  /** Number of transcript commitments */
  commitmentCount: number
  /** SHA-256 of the raw attestation input */
  attestationSha256: string
  /** Verification level: "cryptographic" (Presentation) or "structural" (ProverOutput) */
  verificationLevel: string
  /** Authenticated server hostname (only from Presentation verification) */
  serverName?: string
  /** Sent transcript length in bytes (only from Presentation verification) */
  sentLen?: number
  /** Received transcript length in bytes (only from Presentation verification) */
  recvLen?: number
  /** Revealed sent transcript as UTF-8 (only from Presentation verification) */
  revealedSent?: string
  /** Revealed received transcript as UTF-8 (only from Presentation verification) */
  revealedRecv?: string
  /** TLS connection time as UNIX timestamp (only from Presentation verification) */
  connectionTime?: number
  backend: string
}
export declare function prove(config: ProveConfig): Promise<ProveResult>
/**
 * Try to deserialize the input as a TLSNotary Presentation and perform full
 * cryptographic verification. Falls back to ProverOutput structural check.
 */
export declare function verify(config: VerifyConfig): Promise<VerifyResult>
