/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ProveConfig {
  /** Target HTTPS server hostname (e.g. "api.example.com") */
  serverHost: string
  /** Target HTTPS server port (default 443) */
  serverPort?: number
  /** Notary/verifier TCP address (e.g. "127.0.0.1:7047") */
  notaryHost: string
  notaryPort?: number
  /** HTTP request to send */
  request: HttpRequest
  /** Maximum bytes to send (default 4096) */
  maxSentData?: number
  /** Maximum bytes to receive (default 16384) */
  maxRecvData?: number
  /**
   * Ranges of the response to reveal (byte offsets into recv transcript).
   * If omitted, the entire transcript is revealed.
   */
  revealRanges?: Array<RevealRange>
}
export interface HttpRequest {
  method: string
  path: string
  headers: Array<HttpHeader>
  body?: string
}
export interface HttpHeader {
  name: string
  value: string
}
export interface RevealRange {
  start: number
  end: number
}
export interface ProveResult {
  /** Serialized ProverOutput (commitments + secrets) as JSON */
  attestation: string
  /** SHA-256 of the attestation */
  attestationSha256: string
  /** Server hostname that was proven */
  serverName: string
  /** Sent transcript length in bytes */
  sentLen: number
  /** Received transcript length in bytes */
  recvLen: number
  backend: string
}
export interface VerifyConfig {
  /** Serialized ProverOutput JSON (from ProveResult.attestation) */
  attestation: string
}
export interface VerifyResult {
  /** Whether the attestation deserializes and has valid structure */
  valid: boolean
  /** Number of transcript commitments */
  commitmentCount: number
  /** SHA-256 of the attestation */
  attestationSha256: string
  backend: string
}
export declare function prove(config: ProveConfig): Promise<ProveResult>
export declare function verify(config: VerifyConfig): Promise<VerifyResult>
